### ISSUE TITLE
Warning: undefined is not a function Use --force to continue.

### ISSUE THREAD

**Issue by liuxm6** [anguspiv/grunt-ssi#19]
ssi: {
       options: {
       },
        files: [{
          expand: true,
          cwd: 'html',
          src: ['apps/*.html'],
          dest: 'apps/html'
        }],
    },
Running "ssi:files" (ssi) task
Warning: undefined is not a function Use --force to continue.

Aborted due to warnings.

**Comment by anguspiv** [comment]
Can you post your entire gruntfile? I can't really trace the issue without context. But I think you might be mistaking how Grunt tasks are configured. Try running just `grunt ssi` and see if that works. If not, you may need to create a default task for ssi. Such as
```
ssi: {
  options: {
  },
  someTask: {
     files: [{
       expand: true,
       cwd: 'html',
       src: ['apps/*.html'],
       dest: 'apps/html'
    }]
  },
},
```
then you can run either `grunt ssi` or `grunt ssi:someTask`

for more on task configuration you should read up on Grunt at [http://gruntjs.com/configuring-tasks]()

**Comment by liuxm6** [comment]
Think you very much . I will try again.

发自我的 iPhone
